import {
  pgTable,
  serial,
  integer,
  text,
  boolean,
  timestamp,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { companiesTable } from "./companies";
import { teamMembersTable } from "./teamMembers";

/**
 * One row per *device* a person signs in from.
 *
 * The map used to track a person: one stored position per roster seat. That
 * breaks down the moment somebody works from more than one screen — an owner
 * with a PC, an Android, an iPad and an iPhone had four clients fighting over
 * a single pin that jumped between them. A device is therefore the thing that
 * reports and the thing that gets drawn; the seat is who it belongs to.
 *
 * `deviceKey` is generated by the client and kept locally (localStorage on the
 * web, secure storage on the phone) so the same browser or handset keeps its
 * identity across sessions. It is namespaced per seat by the unique index
 * below, so one person's key can never collide with another's — and, because
 * the seat is always taken from the session and never from the request body,
 * a guessed key cannot be used to write to somebody else's device.
 */
export const staffDevicesTable = pgTable(
  "staff_devices",
  {
    id: serial("id").primaryKey(),
    companyId: integer("company_id")
      .notNull()
      .references(() => companiesTable.id, { onDelete: "cascade" }),
    teamMemberId: integer("team_member_id")
      .notNull()
      .references(() => teamMembersTable.id, { onDelete: "cascade" }),
    /** Stable, client-generated. Unique within a seat, not globally. */
    deviceKey: text("device_key").notNull(),
    /**
     * Opaque, coarse device identity used only to recover a row after app
     * storage is cleared. It is never used to locate or authorize a device.
     */
    recoveryKey: text("recovery_key"),
    /** What the owner sees on the map: "Boss PC", "Richard's iPad". */
    label: text("label").notNull(),
    /** web | ios | android | other — decides the icon, never permission. */
    platform: text("platform").notNull().default("other"),
    /** Last client-reported ability to obtain a location fix. */
    locationHealth: text("location_health").notNull().default("unknown"),
    /**
     * True for the one device (per company) that IS the office. It is a place,
     * not a crew member: the map draws it as a building parked on the stored
     * company office location, and never on whatever the browser last
     * reported. One per company, guaranteed by the partial unique index
     * below — the route's clear-then-set runs in a transaction, and this
     * index makes the invariant hold even against interleaved writers.
     */
    isOffice: boolean("is_office").notNull().default(false),
    /**
     * When this device last reported anything. Kept beside the location row
     * so a device that has been registered but never sent a fix still has an
     * honest "never seen" on the tracking page.
     */
    lastSeenAt: timestamp("last_seen_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    uniqueIndex("staff_devices_member_key_idx").on(
      table.teamMemberId,
      table.deviceKey,
    ),
    uniqueIndex("staff_devices_member_recovery_idx").on(
      table.teamMemberId,
      table.recoveryKey,
    ),
    index("staff_devices_company_id_idx").on(table.companyId),
    // At most ONE office per company, as a database guarantee: two devices
    // both flagged would leave the map picking one arbitrarily.
    uniqueIndex("staff_devices_one_office_idx")
      .on(table.companyId)
      .where(sql`${table.isOffice}`),
  ],
);

export type StaffDevice = typeof staffDevicesTable.$inferSelect;

/**
 * The key the legacy one-row-per-person locations were folded onto at the
 * deploy that introduced devices, and the key a client that hasn't been
 * taught about devices yet still writes to. Sharing one constant keeps the
 * migration's backfill and the API's fallback pointing at the same row
 * instead of quietly creating a second "phone" for the same handset.
 */
export const LEGACY_DEVICE_KEY = "legacy-device";
